version: '3.9'

services:
  wireguard-1:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ${WIREGUARD1_CONTAINER_NAME}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - SERVERPORT=${WIREGUARD1_PORT}
      - PEERS=${WIREGUARD1_PEERS}
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=false
    volumes:
      - ${WIREGUARD1_CONFIG_PATH}:/config
      - ${WIREGUARD1_MODULES_PATH}:/lib/modules
    ports:
      - ${WIREGUARD1_PORT}:${WIREGUARD1_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  wireguard-2:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ${WIREGUARD2_CONTAINER_NAME}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - SERVERPORT=${WIREGUARD2_PORT}
      - PEERS=${WIREGUARD2_PEERS}
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - ${WIREGUARD2_CONFIG_PATH}:/config
      - ${WIREGUARD2_MODULES_PATH}:/lib/modules
    ports:
      - ${WIREGUARD2_PORT}:${WIREGUARD2_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped